/**
 * Minimal synthetic case used by engine unit tests. Exercises each engine
 * mechanism in isolation; it is NOT part of the shipped library and is not
 * exported from the package barrel.
 */

import type { SimulationCaseDefinition } from './types';
import { SIMULATION_ENGINE_VERSION } from './types';

export function makeTestCase(): SimulationCaseDefinition {
  return {
    caseId: 'test_case',
    title: 'Test case',
    description: 'Engine unit-test fixture.',
    difficulty: 'easy',
    scenarioType: 'general',
    estimatedDurationMinutes: 10,
    caseVersion: 1,
    engineVersion: SIMULATION_ENGINE_VERSION,
    patient: {
      name: 'Test Patient',
      age: 40,
      sex: 'female',
      allergies: [],
      codeStatus: 'Full code',
      chiefComplaint: 'Test',
      admittingDiagnosis: 'Test',
      history: [],
      homeMedications: [],
      baselineVitals: { hr: 80, spo2: 97 },
    },
    phases: ['p1', 'p2'],
    initialPhase: 'p1',
    phaseFlow: { p1: ['p2'], p2: [] },
    initialVitals: { hr: 100, spo2: 90 },
    findings: [
      {
        id: 'f_a',
        system: 'respiratory',
        text: 'Finding A (present).',
        presentAtStart: true,
        keyCue: true,
      },
      {
        id: 'f_b',
        system: 'respiratory',
        text: 'Finding B (absent).',
        presentAtStart: false,
        keyCue: false,
      },
      {
        id: 'f_c',
        system: 'skin',
        text: 'Finding C (present).',
        presentAtStart: true,
        keyCue: false,
      },
    ],
    labs: [
      { id: 'lab_x', name: 'Lab X', unit: 'u', value: 5, flag: 'high', availableAtStart: false },
    ],
    medicationOrders: [],
    actions: [
      {
        id: 'act_assess',
        type: 'assess',
        label: 'Assess respiratory',
        timeCostMinutes: 2,
        revealsSystems: ['respiratory'],
        classification: { default: 'appropriate' },
      },
      {
        id: 'act_assess_gu',
        type: 'assess',
        label: 'Assess GU',
        timeCostMinutes: 1,
        revealsSystems: ['gu'],
        classification: { default: 'unnecessary' },
      },
      {
        id: 'act_vitals',
        type: 'obtain_vitals',
        label: 'Obtain vitals',
        timeCostMinutes: 1,
        observesVitals: true,
        classification: { default: 'appropriate' },
      },
      {
        id: 'act_boost',
        type: 'administer_medication',
        label: 'Give boost med',
        timeCostMinutes: 1,
        classification: { default: 'appropriate' },
      },
      {
        id: 'act_cancel',
        type: 'hold_medication',
        label: 'Cancel pending effect',
        timeCostMinutes: 1,
        classification: { default: 'appropriate' },
      },
      {
        id: 'act_crash',
        type: 'administer_medication',
        label: 'Crash vitals',
        timeCostMinutes: 1,
        classification: { default: 'unsafe' },
      },
      {
        id: 'act_ask',
        type: 'ask_patient',
        label: 'Ask',
        timeCostMinutes: 1,
        promptRequired: true,
        classification: { default: 'appropriate' },
      },
      {
        id: 'act_class',
        type: 'wait',
        label: 'Phase-classified action',
        timeCostMinutes: 1,
        classification: { default: 'appropriate', byPhase: { p2: 'unsafe' } },
      },
      {
        id: 'act_end',
        type: 'notify_provider',
        label: 'End now',
        timeCostMinutes: 1,
        classification: { default: 'appropriate' },
      },
      {
        id: 'act_wait',
        type: 'wait',
        label: 'Wait 5',
        timeCostMinutes: 5,
        classification: { default: 'appropriate' },
      },
      {
        id: 'act_free',
        type: 'wait',
        label: 'Zero-cost action',
        timeCostMinutes: 0,
        classification: { default: 'appropriate' },
      },
    ],
    dialogue: [
      {
        id: 'dp_q',
        question: 'Gated question?',
        response: 'Full answer.',
        requiresFindingRevealed: 'f_a',
        gatedResponse: 'Gated answer.',
      },
    ],
    statements: [{ id: 'st_hello', text: 'Hello there.' }],
    rules: [
      {
        id: 'r_boost',
        description: 'Boost raised SpO2 and scheduled HR recovery, moving to p2.',
        trigger: { kind: 'action', actionId: 'act_boost' },
        conditions: [],
        effects: [
          { kind: 'vital_delta', vital: 'spo2', delta: 5, max: 93 },
          { kind: 'set_phase', phase: 'p2' },
          {
            kind: 'schedule',
            scheduleId: 'sch_later',
            afterMinutes: 5,
            effects: [{ kind: 'vital_delta', vital: 'hr', delta: -10, min: 60 }],
          },
          { kind: 'release_lab', labId: 'lab_x' },
          { kind: 'patient_statement', statementId: 'st_hello' },
        ],
        once: true,
      },
      {
        id: 'r_cancel',
        description: 'Cancelled the pending effect.',
        trigger: { kind: 'action', actionId: 'act_cancel' },
        conditions: [],
        effects: [{ kind: 'cancel_scheduled', scheduleId: 'sch_later' }],
        once: true,
      },
      {
        id: 'r_crash',
        description: 'Crash pushed SpO2 far below any survivable value.',
        trigger: { kind: 'action', actionId: 'act_crash' },
        conditions: [],
        effects: [{ kind: 'vital_delta', vital: 'spo2', delta: -100 }],
        once: true,
      },
      {
        id: 'r_on_p2',
        description: 'Entering p2 set a flag.',
        trigger: { kind: 'phase_enter', phase: 'p2' },
        conditions: [],
        effects: [{ kind: 'add_flag', flag: 'entered_p2' }],
        once: true,
      },
      {
        id: 'r_time10',
        description: 'At 10 minutes the heart rate rose.',
        trigger: { kind: 'time' },
        conditions: [{ kind: 'time_at_least', minutes: 10 }],
        effects: [{ kind: 'vital_delta', vital: 'hr', delta: 10, max: 220 }],
        once: true,
      },
      {
        id: 'r_end_now',
        description: 'Notifying ended the scenario.',
        trigger: { kind: 'action', actionId: 'act_end' },
        conditions: [],
        effects: [{ kind: 'end', outcomeId: 'o_done' }],
        once: true,
      },
      {
        id: 'r_deadline',
        description: 'Time limit reached.',
        trigger: { kind: 'time' },
        conditions: [{ kind: 'time_at_least', minutes: 60 }],
        effects: [{ kind: 'end', outcomeId: 'o_timeout' }],
        once: true,
      },
    ],
    outcomes: [
      { id: 'o_done', kind: 'stabilized', label: 'Done', summary: 'Ended by notify.' },
      { id: 'o_timeout', kind: 'timeout', label: 'Timed out', summary: 'Ended by deadline.' },
    ],
    criticalActions: [
      { id: 'ca_vitals', label: 'Obtain vitals', anyOfActionIds: ['act_vitals'], byMinutes: 30 },
    ],
    scoring: [
      {
        id: 's_vitals',
        dimension: 'recognize_cues',
        points: 1,
        criterion: { kind: 'vitals_obtained' },
        label: 'Obtained vitals.',
      },
    ],
    conceptMappings: [],
    debriefRecommendations: ['Test topic'],
  };
}
